apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-service
  labels:
    app: todo-frontend
spec:
  type: NodePort
  selector:
    app: todo-frontend
  ports:
  - port: {{ .Values.frontend.port }}
    targetPort: {{ .Values.frontend.port }}
    nodePort: 30080