apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
type: Opaque
data:
  DATABASE_URL: {{ .Values.env.databaseUrl | b64enc }}
  COHERE_API_KEY: {{ .Values.env.cohereApiKey | b64enc }}
  BETTER_AUTH_SECRET: {{ .Values.env.betterAuthSecret | b64enc }}